### ISSUE TITLE
[question] How to collect consumer group metrics from Confluent Cloud?

### ISSUE THREAD

**Issue by peimanja** [cloudworkz/kafka-minion#12]
Our brokers are running on [Confluent Cloud](https://docs.confluent.io/current/cloud/index.html) and we have a VPC peering enabled there and that's how we are connected.

Kafka version: 2.2.1

I was able to run the exporter and successfully collect Topic / Partition metrics but it seems there is no `__consumer_offsets` topic. 
I see below topics tho but do not think any of them works:
```
__consumer_timestamps
_confluent-monitoring
_confluent-metrics
_confluent-command
```
could anyone figure out how to get those metrics?

**Comment by weeco** [comment]
Hey, unfortunately I do not have any experience with Confluent Cloud, but I'd guess it's a restricted topic and therefore you cannot use tools like Kafka Minion or Burrow.

Maybe you have a chance to ask Confluent whether or not it is possible to consume the `__consumer_offsets` topic and enlighten us afterwards?

**Comment by peimanja** [comment]
> Hey, unfortunately I do not have any experience with Confluent Cloud, but I'd guess it's a restricted topic and therefore you cannot use tools like Kafka Minion or Burrow.
> 
> Maybe you have a chance to ask Confluent whether or not it is possible to consume the `__consumer_offsets` topic and enlighten us afterwards?

Thanks for the respond. I will ask on Monday and see what they say. Will update here.

**Comment by peimanja** [comment]
Respond from Confluent Cloud support:
>It seems this topic is made invisible by default, as It has data from all tenants.  If it's made visible, it will risk leaking information. 
I've confirmed with engineering on that. 
Currently there's only the API that might be able to do what you wanted.  However it requires you have cloud cli installed though. 
See https://docs.confluent.io/current/cloud/using/monitor-lag.html#monitor-offset-lag-via-broker-apis
Your monitoring application should be able to accomodate this setup,  hopefully that does what you wanted.

I wonder if there is a way to use the method described in https://docs.confluent.io/current/cloud/using/monitor-lag.html#monitor-offset-lag-via-broker-apis
and expose that as Prometheus metrics

**Comment by weeco** [comment]
HEy @peimanja , thanks for sharing the response. I suspected that. When developing Kafka Minion I had the option to use the Kafka Broker API or to directly consume the offsets topic.

Initially Kafka Minion was developed using the Broker API but we had some issues and we wanted to get more metrics which we could only get from the offsets topic. I believe that's the biggest advantage of this exporter. To keep this exporter "simple" I do not intend to add an option to use the Broker API instead of the consumer offsets topic either.

I'd recommend you to take a look at Daniel's exporter which uses the mentioned Broker APIs: https://github.com/danielqsj/kafka_exporter
